### ISSUE TITLE
Clear up the manager implementation.

### ISSUE THREAD

**Issue by atheriel** [OSPokemon/api-java#10]
Managers should be finished (that is, working and fairly consistent) by `0.1`. This means:
- All objects that are likely to be managed (including Species, Natures, Moves, Items, Abilities) should have a consistent, optional `manager` reference.
- There should be a working implementation of the `Manager<T>` for each of these manageable objects, either using a generic `SimpleManager<T>`, or one that is unique to the class (i.e. `TypeManager`).

We could possibly move these implementations to a `org.jpokemon.api.manager` subpackage.

@zachtaylor

**Comment by zachtaylor** [comment]
`org.jpokemon.api.manager` sounds like a good namespace! And, `SimpleManager<T>` provides a good base for data bindings to use or extend

**Comment by atheriel** [comment]
Oh god. I didn't realize you were committing to that branch.... I have literally hundreds of merge conflicts now. My bad.

**Comment by zachtaylor** [comment]
I just realized I tagged the wrong issue from a commit.

**Comment by atheriel** [comment]
This is _mostly_ done right now. The `managers` subpackage contains classes for managing Abilities, Natures, Items, Moves, and Types. There isn't one for Species at the moment. It also contains the `SimpleManager<T>` class.

I've kept the `Manager<T>` interface in the top-level directory, as per convention.
