### ISSUE TITLE
Add Ball, (Hidden) Machine, and Medicine ItemAttributes.

### ISSUE THREAD

**Issue by atheriel** [OSPokemon/api-java#12]
Currently, there are only two `ItemAttribute` implementations available, BerryAttribute and PocketAttribute. I propose that this list could be rounded out nicely with 
- BallAttribute
  - new `catchRateModifier` field
- MachineAttribute
  - new `moveTaught` field
- MedicineAttribute
  - `onUse` method?

Other attributes that might be nice are ones that refer to stat-boosting items (Protein, Calcium, etc) and ones that affect in-battle stats (X-Attack, etc).

**Comment by zachtaylor** [comment]
I completely agree with the attribute system. It also provides a hook for people to write custom item attributes like `CanOnlyUseAgainstWaterTypeAttribute`, `EvolutionStoneAttribute`, etc.

But, do we need items to refer to their attributes by string name? If so, attributes can't take parameters, such as item strength, etc, which is just something to note - not a problem!

**Comment by zachtaylor** [comment]
@atheriel BerryAttribute could provide a "time takes to grow" field

**Comment by zachtaylor** [comment]
link 55d3aff66ce1a1c2e15886589bcbb565a1bb5e2d

**Comment by zachtaylor** [comment]
link 4b7d050302c5ae50b9946a21c9b3d61dc459af9d
