### ISSUE TITLE
PokemonAbility, PokemonNature, and PokemonSpecies could be renamed.

### ISSUE THREAD

**Issue by atheriel** [OSPokemon/api-java#15]
It's not like the "Pokemon" prefix is necessary.

**Comment by zachtaylor** [comment]
Sounds good. This issue can be lumped in with something else, since a renaming branch seems excessive.

**Comment by atheriel** [comment]
I suggest #17 -- it makes it into a small refactor.

**Comment by zachtaylor** [comment]
Sounds good. I'll edit the issue to combine them and close this one.
