### ISSUE TITLE
Packing and Naming conventions

### ISSUE THREAD

**Issue by atheriel** [OSPokemon/api-java#17]
Namespaces without multiple classes should be flattened.
- Types
- Natures
- Species

Classes with names named Pokemon\* should be shortened.
- PokemonAbility
- PokemonNature
- PokemonSpecies

**Comment by atheriel** [comment]
Do you want to handle this one?

**Comment by atheriel** [comment]
Also, I think we should move `JPokemonError` and `JPokemonException` to an `errors` subpackage.

**Comment by zachtaylor** [comment]
Oh yeah, I wanted to mention this to you. I read that errors are considered [worse than exceptions](http://docs.oracle.com/javase/7/docs/api/java/lang/Error.html)

I would like namespacing exceptions the same way we namespaced managers

Yeah I'll take this one. Is everything merged and safe?

**Comment by atheriel** [comment]
Merged and safe, although failing unit tests until they are rewritten.

I dislike using exceptions for anything that shouldn't crash the program, and most of the time when `JPokemonError` is actually used having to wrap it in a try{..} catch {...} block would be extremely annoying -- constructors, for example.

**Comment by atheriel** [comment]
Renamed PokemonAbility to Ability, since it seems to have been missed.

ps. I can't believe Type is an allowed class name in Java....
