### ISSUE TITLE
String-based item attribute system.

### ISSUE THREAD

**Issue by atheriel** [OSPokemon/api-java#23]
Following up on some earlier discussion by email, we need to move the ItemAttribute system away from the current model to a key-value system with strings.

Attributes with a logical grouping (i.e. things that berries have, or things that medicines have) should implement the ItemAttribute interface for clarity and define fields for the attributes. They should also have static methods for adding the attributes to the item/retrieving an attribute from an item, presumably by converting the values of the fields to strings, and vice versa.

**Comment by zachtaylor** [comment]
I suggest `Item.(get/set)Property` instead of `Item.(get/set)Attribute`
I just want to clarify the difference between an `ItemAttribute` being composed of an `Item`'s `properties` (or vice versa, or different naming)

**Comment by atheriel** [comment]
I used `Attribute` primarily to make sure it wasn't confused with `Effect`. `Property` sounds more ambiguous, but I don't really have a strong opinion on the matter.
